### ISSUE TITLE
Propagating the timestamp through to the EventEnvelope

### ISSUE THREAD

**Issue by bennichols** [serverlesstechnology/cqrs#17]
Hi, I'm working on some views where I want to send the traditional `created_at` and `updated_at` fields to the front end. All the data for this can be easily derived from the timestamp field, so I'd like to use it, but it isn't surfaced by the EventEnvelope. I realise that currently there is no dependency on any DateTime libraries, so this isn't a trivial change, but it seems like the alternative is to store the timestamp in each event, which is less than ideal. Do you have any other thoughts on how this can be approached?

Thanks!

**Comment by davegarred** [comment]
Hello @bennichols,  thanks for the interest.

When you say "send to the front end", I'm assuming you would like to add this to your query handler so that the materialized views can track this information. Please correct me if you are asking something else.

The timestamp field is designed to store the time that the event was committed from the database's perspective. It's more of a debugging/administrative tool and isn't really designed to provide any utility past that.

The best solution is add a `time` field to your metadata that can be used for this information, an example for this is found in the `cqrs-demo` repository.
- [adding time to metadata](https://github.com/serverlesstechnology/cqrs-demo/blob/master/src/metadata_extension.rs#L15)
- [processing a command with provided metadata](https://github.com/serverlesstechnology/cqrs-demo/blob/master/src/main.rs#L87-L89)


The `metadata` field is the place to put any information that needs to be retained but is not involved with business logic.

**Comment by bennichols** [comment]
Yes, that's what I mean, to use the timestamp for a materialised view. I'm unclear why the timestamp can't be used for more. It will have the exact same data as the timestamp in the metadata, so it feels redundant. Furthermore, if it is for debugging, I'd want to shunt the events off to a logging service, in which case I'd want it in the event envelope anyway. It doesn't seem like having it only accessible when directly viewing the database adds much utility beyond trivial debugging.

**Comment by bennichols** [comment]
Ok, that makes sense. Thanks for the your help and all your work on the lib!
