### ISSUE TITLE
Either make EventStore public or have some kind of accessor?

### ISSUE THREAD

**Issue by bennichols** [serverlesstechnology/cqrs#18]
Hi again! One use case I've run into recently is sometimes I want to build an aggregate without a command to send it. It might be in lieu of a query where the query would be overkill or as part of a query processor chain. In order to do this, I can call `load_aggregate` on the EventStore object and call the `aggregate()` method. Unfortunately, there is no public handle to the EventStore member in the CqrsFramework struct, so I have to create duplicate EventSource objects that I pass along to my axum routes. This works fine, but it would be a lot nicer if either the EventSource was public or I could access it somehow. What are your thoughts?

**Comment by bennichols** [comment]
No, they don't. Bottom line is, there are times when I'll need to build an aggregate outside of the context of a command. For this particular case, it's because I don't think it's worth building a query at this point for a few events while the business logic is still being developed. But there are other use cases, including your first example above, and I don't believe that's always the right answer. I try to avoid words like "never" when talking about architecture, because if our jobs were as simple as following a strict set of rules, then it would be a lot more straightforward than it is (and a lot less interesting). In my deep dive on CQRS and Event Sourcing, I've watched/read many hours/pages of opinions, and the consensus among the experts seems to be: it's a set of guidelines, not rules, and you should break the rules when it makes sense. 

Long story short, your framework allows me to do what I want. While the common consensus is also "don't use frameworks", I like that yours streamlines code I would have to write anyway and lets me design my system as I see fit. I can do what I want using a combination of the CqrsFramework and the EventStore object I use to initialise it. It's just not as nice as it could be, because I can't access that EventStore object directly through the CqrsFramework (even though I'm the one who put it there, so it's not really private), and I have to make another instance of the EventStore object to pass around, so all my axum extensions are tuples of both instead of a singular object. I realise you state from the get-go that the framework is opinionated and I'm certainly not telling anyone else how it should work, but I did want to let you know how I'm using it and how it could be slightly more convenient for me. Cheers.

**Comment by serverlesstechnology** [comment]
One of the primary benefits of CQRS is the separation of business logic changes from the readable state of the system. The aggregate _must_ stay private in order to ensure the integrity of this functionality.

Note that you can use an [event repository](https://docs.rs/cqrs-es/0.3.2/cqrs_es/persist/trait.PersistedEventRepository.html) (the backing behind the event store) to access these events directly. E.g., [`PostgresEventRepository`](https://docs.rs/postgres-es/latest/postgres_es/struct.PostgresEventRepository.html).

This sort of access is commonly used to do things such as:
- stream events to new sources
- replay events to a new or updated query
- provide event-sourcing to an external system dependent on the aggregate
