### ISSUE TITLE
Garbage collect old events

### ISSUE THREAD

**Issue by peteole** [serverlesstechnology/cqrs#19]
Hi,

I've just read the book about this repo and am really excited about it!

However I am a bit worried about the size of the event store. Is there some kind of garbage collection for old events?

For instance let's say we have a system where only a known set of agents may write commands. For some time it makes sense to store the set of commands since due to networking latency, some commands may arrive delayed. However when we received some message from all writing agents, we may safely assume that the state of our system does not change at the point where we are sure to have received all commands to that point in time. Therefore we might calculate the state at that point, take it as new "start" and delete the events before, saving a lot of memory.
Kind of like a concept called snapshots I read about, but to save storage, not computation time.

Or do I overestimate the problem the indefinitely growing event/command logs are?

**Comment by peteole** [comment]
By the way I'm quite new to event sourcing, so please excuse if I misunderstood a concept. I'm just evaluating if I should use event sourcing for a project and this is a major point of concern I have

**Comment by serverlesstechnology** [comment]
Hi @peteole, thanks for the interest and welcome to event sourcing!

If you select the `Snapshot` or `Aggregate` source of truth you will have the option to truncate old events, but that truncation will incapacitate all the flexibility that event sourcing provided.

The solution that I've had the most success with is archiving entire aggregate instances. In the bank account example from the book that might look something like:
- Identify and delete any accounts that are inactive for more than 24 months (a "delete" in event sourcing is just an event that marks it as deleted, as well as some logic to reject any new commands after that point).
- Back up, export or otherwise ensure that all views referencing this account are not deleted or further modified. I prefer a "legacy" read-only system to store the views of deleted aggregates.
- Delete all of the events that correspond to that aggregate id in your production database.

**Comment by peteole** [comment]
Hi, thank you for your advice! Maybe I overestimated the storage size benefits that an aggregate has over a list of events in my domain. I want to build a decentralized photo management software similar to Google Photos. The most important feature will be shared albums. The metadata of each shared album (the list of all photo IDs in that album) should be an aggregate. The events would be "Person X added photo Y" or "Person X removed photo Y". The events would be synchronized using a decentralized PubSub with Libp2p and be persisted in a local database replica on each peer. There would need to be a mechanism to ensure all events by a peer arrived such as including a hash of the previous event by the peer in each event. It is critical that it may take days before an event propagated to all the peers in case of a bad connection and may arrive in arbitrary order. Also albums may get really huge (in the order of one million photos) since there should be an album containing all the photos for backup with a raspberry pi.
Do you think that Event Sourcing is a good idea for this problem?
One main benefit I am hoping for is that an optimistic view of the aggregate can be computed easily even if not all events up to that point have been synchronized yet since events "arriving late" can easily be put in the event queue at their place afterwards. Do I see this correctly?

**Comment by serverlesstechnology** [comment]
Hi @peteole , whether CQRS is right for you will depend on the complexity of your logic, but I think event-sourcing is the wrong answer here. 

Event sourcing requires that _all_ events be read before any change is made which would be very difficult at that scale. Storing that many events in a database is certainly not an issue, but trying to load them for each command would be cumbersome to say the least.

Instead, should you decide to use CQRS, I would recommend using a source of truth of either an [aggregate](https://docs.rs/cqrs-es/0.3.2/cqrs_es/persist/struct.PersistedEventStore.html#method.new_aggregate_store) or a [snapshot-backed](https://docs.rs/cqrs-es/0.3.2/cqrs_es/persist/struct.PersistedEventStore.html#method.new_snapshot_store) event store.
