### ISSUE TITLE
Some questions and suggestions

### ISSUE THREAD

**Issue by dpc** [serverlesstechnology/cqrs#25]
First some basic suggestion: please enable Discussion for this project and/or make some Matrix channel etc. for users to hang out in, ask for help and socialize. Had it been already there, I would have just asked there. :)

I wanted to start using "event processing" (write stuff down in a log, and then have other stuff follow that log and react to it) in my Rust projects. I did not specifically thought about ES/CQRS but I think what I wanted to achieve might fit in this model.

Your crate looks like a solid, more informed base and I went through the book, read through the demo code and some of the source code and I think I can find myself here. I like that it's lightweight, to the point and supports Postgres. Great job.

I basically want to write a CI/CD bot to power my [fake Rust/Nix software shop](https://github.com/rustshop/rustshop). I'm thinking - I consume github webhooks as "Commands", I track aggregates like "PR" (PR, commits in it, all the pushes, all the builds).

Q1: **Are `Queries`eagerly and reactive**? I mean - on every new event, I can expect the "simple query" to be called eagerly and in it's code I can emit any side effects(?) like starting a new CI build? Is it guaranteed? The ("it's useless in production"](https://github.com/serverlesstechnology/cqrs-demo/blob/50029766363aa0ff324ccd264bdeed532e5a236e/src/queries.rs#L12) is a bit confusing. I guess the framework itself does not keep track of which events each query processed already, so I would have to persist some "pointer" to skip emitting side effects for events I already reacted to before (some idempotency-like considerations), but otherwise that's it? BTW. You might want to consider building a concept of a "Reactor" or something that would wrap a Query and keep track of position in the event stream automatically - seems rather generic.

Q2: **How do I approach multiple event streams including splitting between multiple "microservices"**? The demos are kind of simplistic and include only one aggregate. I might just need to read more literature, since it's more of an architecture question, but if you could give me a pointer or two, I would appreciate it. 

I guess I can have multiple programs using  `cqrs` library pointing at the same DB in Postgres and one (or even more) of them writing events, and all following new events. I do realize  that I can have things like CDC with Kafka/Kinesis etc. but it's kind of heavy for my tiny internal tools use, at least for now.

Anyway, thanks for your work on this project, and sooner or later I'll figure it out and maybe post some links with results.

**Comment by dpc** [comment]
> can expect the "simple query" to be called eagerly and in it's code I can emit any side effects(?) like starting a new CI build? Is it guaranteed?

The code says it always happens.

https://github.com/serverlesstechnology/cqrs/blob/86d83dc5bb773742513bd2a60e42d219dff92e58/src/cqrs.rs#L187

However they seem to be called after they are commited, which seems like a bug that can result in loosing an event. I'll report in another issue.

**Comment by dpc** [comment]
> I guess for that I'll have to write my own thing that will poll for new events and then dispatch them to queries manually.

But the schema doesn't have any global id that would be monotonically increasing so I guess that won't fly, unless I want to subscribe to particular aggregate updates or something. Hmm...

**Comment by serverlesstechnology** [comment]
Hi @dpc, Discussion is now on, thanks for the suggestion.

Thanks also for your feedback on these crates, to your open questions:

#### Are `Queries` eager and reactive?
Very much so, new events will be pushed a single time to each query immediately after they are committed. To guarantee delivery your query will need to take the responsibility of tracking the status of each event. The simplest way to do this is to add an additional boolean field to the event table for each query that needs this guarantee.

E.g., your event table may look something like this:
```
CREATE TABLE events
(
    aggregate_type               text           NOT NULL,
    ...
    delivered_to_account_query   boolean        NOT NULL,
    PRIMARY KEY (aggregate_type, aggregate_id, sequence)
);
```

This new field serves as a delivery flag and after you have successfully delivered the event to the query the field should be updated to reflect this status. If the query is local in the same database this gives you a very simple two-phase commit guarantee, otherwise you'll need to take precautions to avoid more-than-once delivery to a remote service (if that is a concern to you).


#### How do I approach multiple event streams including splitting between multiple "microservices"? 
I'm not sure that I totally understand the context of your question, but there is rarely a guarantee of which event will arrive at any destination first. Thus, you'll want to treat events that are produced from multiple aggregate as asynchrounous events and take all the precautions that might be needed for your domain.

**Comment by serverlesstechnology** [comment]
> > I guess for that I'll have to write my own thing that will poll for new events and then dispatch them to queries manually.
> 
> But the schema doesn't have any global id that would be monotonically increasing so I guess that won't fly, unless I want to subscribe to particular aggregate updates or something. Hmm...

Every event should be globally unique via the composite id of `aggregate_type`, `aggregate_id` and `sequence`.

**Comment by serverlesstechnology** [comment]
> Also, AFAICT the queries handling event will block the event processing, so they better be fast

This is accurate. If response latency is a priority it would be better to use a custom query to hand the events off to another thread for delivery.
