### ISSUE TITLE
Possibility of queries loosing an event.

### ISSUE THREAD

**Issue by dpc** [serverlesstechnology/cqrs#26]
https://github.com/serverlesstechnology/cqrs/blob/86d83dc5bb773742513bd2a60e42d219dff92e58/src/cqrs.rs#L187

```rust
        let committed_events = self
            .store
            .commit(resultant_events, aggregate_context, metadata)
            .await?;
        for processor in &self.queries {
            let dispatch_events = committed_events.as_slice();
            processor.dispatch(aggregate_id, dispatch_events).await;
        }
```

if the program crashes between committing and dispatching to queries, the queries might never see events. Is this on purpose? I would expect that to guarantee at least once delivery the dispatch should be done first, and commit later, but I'm somewhat of a noob.

**Comment by tk-o** [comment]
If any event fails to be stored, there should be no side-effect triggered (as the aggregate would not effectively transition its state).

The `AggregateError<A::Error>` error will be returned to the caller, and it can decide what to do next (maybe retry the `execute` function call, or maybe drop the attempt of handling the problematic command.

At least that's what I believe is the case 🙃

**Comment by serverlesstechnology** [comment]
@dpc You are correct that the design here is to commit immediately after the command completes and before the events are published to queries. A query failure to send or process an event should never result in a failure to commit the events.

Additionally, queries may be asynchronous, highly distributed, or otherwise rigidly decoupled from the events (and commands that produce them), and so are are expected to need additional logic to recognize and recover from missing events. Recognition is done most simply though tracking the latest sequence number for an aggregate instance and recovery via an [event replay](https://docs.rs/cqrs-es/latest/cqrs_es/persist/struct.QueryReplay.html).
